### ISSUE TITLE
Quaternions

### ISSUE THREAD

**Issue by sujaymanb** [CSUHuman-UAV-UGV-Collaboration/bebop_control#1]
The pose of the ar_marker provides us the orientation in quaternions.  I need some way to find the difference in the angle of the drone vs the marker and align the drone accordingly.

**Comment by sujaymanb** [comment]
I think one possible approach would be to convert the quaternions (x,y,z,w), which is confusing, into euler (roll, pitch, yaw).

**Comment by shiqizhang6** [comment]
@sujaymanb In case you didn't know this:
http://wiki.ros.org/tf2/Tutorials/Quaternions

**Comment by sujaymanb** [comment]
Converting to euler is a good solution
